import bcrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "adminUser",
      email: "admin@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "customerUser",
      email: "customer@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "p1",
      category: "cat1",
      countInStock: 1,
      rating: 1,
      price: 100,
      img: "/images/p1.jpg",
      numReviews: 1,
      description: "d1",
    },
    {
      name: "p2",
      category: "cat2",
      countInStock: 2,
      rating: 2,
      price: 200,
      img: "/images/p2.jpg",
      numReviews: 2,
      description: "d2",
    },
    {
      name: "p3",
      category: "cat3",
      countInStock: 3,
      rating: 3,
      price: 300,
      img: "/images/p3.jpg",
      numReviews: 3,
      description: "d3",
    },
    {
      name: "p4",
      category: "cat4",
      countInStock: 4,
      rating: 4,
      price: 400,
      img: "/images/p4.jpg",
      numReviews: 4,
      description: "d4",
    },
    {
      name: "p5",
      category: "cat5",
      countInStock: 5,
      rating: 4.5,
      price: 500,
      img: "/images/p5.jpg",
      numReviews: 5,
      description: "d5",
    },
    {
      name: "p6",
      category: "cat6",
      countInStock: 6,
      rating: 5,
      price: 600,
      img: "/images/p6.jpg",
      numReviews: 6,
      description: "d6",
    },
  ],
};

export default data;
