const data = {
  products: [
    {
      _id:1,
      name: "מוצר 1",
      category: "cat1",
      countInStock: 1,
      rating: 1,
      price: 100,
      image: "/images/p1.jpg",
      numReviews: 1,
      description: "d1",
    },
    {
      _id:2,
      name: "מוצר 2",
      category: "cat2",
      countInStock: 2,
      rating: 2,
      price: 200,
      image: "/images/p2.jpg",
      numReviews: 2,
      description: "d2",
    },
    {
      _id:3,
      name: "מוצר 3",
      category: "cat3",
      countInStock: 3,
      rating: 3,
      price: 300,
      image: "/images/p3.jpg",
      numReviews: 3,
      description: "d3",
    },
    {
      _id:4,
      name: "מוצר 4",
      category: "cat4",
      countInStock: 4,
      rating: 4,
      price: 400,
      image: "/images/p4.jpg",
      numReviews: 4,
      description: "d4",
    },
    {
      _id:5,
      name: "מוצר 5",
      category: "cat5",
      countInStock: 5,
      rating: 4.5,
      price: 500,
      image: "/images/p5.jpg",
      numReviews: 5,
      description: "d5",
    },
    {
      _id:6,
      name: "מוצר 6",
      category: "cat6",
      countInStock: 6,
      rating: 5,
      price: 600,
      image: "/images/p6.jpg",
      numReviews: 6,
      description: "d6",
    },
  ],
};

export default data;
